package auth

import (
	"context"
	"crypto/rsa"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

// Google OIDC client (18 Agu 2026). Implements the server side of the
// Authorization Code flow: building the consent redirect URL, exchanging the
// authorization code, and verifying the returned id_token against Google's
// JWKS. No third-party OAuth dependency — everything runs over the stdlib
// HTTP client with explicit timeouts and request contexts (SEC-26).

const (
	// GoogleAuthURL is the OAuth 2.0 authorization endpoint.
	GoogleAuthURL = "https://accounts.google.com/o/oauth2/v2/auth"
	// googleTokenURL exchanges an authorization code for tokens.
	googleTokenURL = "https://oauth2.googleapis.com/token"
	// googleJWKSURL publishes Google's signing keys for id_token verification.
	googleJWKSURL = "https://www.googleapis.com/oauth2/v3/certs"
	// googleScope is the minimal scope set: identity + email + display name.
	googleScope = "openid email profile"
	// jwksCacheTTL bounds how long a fetched JWKS is trusted before refetch.
	jwksCacheTTL = 15 * time.Minute
)

// Sentinel errors surfaced by the Google flow. Callers match with errors.Is
// (SEC-28) — never string-compare.
var (
	ErrGoogleExchangeFailed   = errors.New("google code exchange failed")
	ErrGoogleInvalidIDToken   = errors.New("google id_token invalid")
	ErrGoogleEmailUnverified  = errors.New("google email not verified")
	ErrGoogleNonceMismatch    = errors.New("google id_token nonce mismatch")
	ErrGoogleMissingIDToken   = errors.New("google token response missing id_token")
	ErrGoogleJWKSUnavailable  = errors.New("google jwks unavailable")
	ErrGoogleUnknownKeyID     = errors.New("google id_token signed with unknown key id")
	ErrGoogleUnexpectedIssuer = errors.New("google id_token unexpected issuer")
)

// GoogleIdentity is the verified identity extracted from a Google id_token.
type GoogleIdentity struct {
	Subject       string // immutable `sub` claim — the stable account key
	Email         string
	EmailVerified bool
	Name          string
}

// GoogleClient talks to Google's OAuth/OIDC endpoints.
type GoogleClient struct {
	clientID     string
	clientSecret string
	redirectURI  string
	http         *http.Client

	mu        sync.RWMutex
	jwks      map[string]*rsa.PublicKey // kid -> public key
	jwksFetch time.Time
}

func NewGoogleClient(clientID, clientSecret, redirectURI string) *GoogleClient {
	return &GoogleClient{
		clientID:     clientID,
		clientSecret: clientSecret,
		redirectURI:  redirectURI,
		http:         &http.Client{Timeout: 10 * time.Second},
		jwks:         map[string]*rsa.PublicKey{},
	}
}

// AuthCodeURL builds the Google consent-screen redirect. `state` (CSRF) and
// `nonce` (id_token binding) are generated by the caller and persisted
// server-side; both are echoed back and re-validated on callback.
func (g *GoogleClient) AuthCodeURL(state, nonce string) string {
	q := url.Values{}
	q.Set("client_id", g.clientID)
	q.Set("redirect_uri", g.redirectURI)
	q.Set("response_type", "code")
	q.Set("scope", googleScope)
	q.Set("state", state)
	q.Set("nonce", nonce)
	// Force the account chooser so shared-device users can switch accounts.
	q.Set("prompt", "select_account")
	return GoogleAuthURL + "?" + q.Encode()
}

// googleTokenResponse is the subset of the token endpoint response we use.
type googleTokenResponse struct {
	IDToken string `json:"id_token"`
}

// googleIDClaims mirrors the Google id_token claims we validate/extract.
type googleIDClaims struct {
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	Name          string `json:"name"`
	Nonce         string `json:"nonce"`
	jwt.RegisteredClaims
}

// Exchange trades an authorization code for tokens, then verifies the
// id_token (signature via JWKS, iss/aud/exp, and the flow nonce).
func (g *GoogleClient) Exchange(ctx context.Context, code, expectedNonce string) (GoogleIdentity, error) {
	form := url.Values{}
	form.Set("code", code)
	form.Set("client_id", g.clientID)
	form.Set("client_secret", g.clientSecret)
	form.Set("redirect_uri", g.redirectURI)
	form.Set("grant_type", "authorization_code")

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, googleTokenURL, strings.NewReader(form.Encode()))
	if err != nil {
		return GoogleIdentity{}, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	res, err := g.http.Do(req)
	if err != nil {
		return GoogleIdentity{}, fmt.Errorf("%w: %v", ErrGoogleExchangeFailed, err)
	}
	defer res.Body.Close()
	body, err := io.ReadAll(io.LimitReader(res.Body, 1<<20))
	if err != nil {
		return GoogleIdentity{}, fmt.Errorf("%w: %v", ErrGoogleExchangeFailed, err)
	}
	if res.StatusCode != http.StatusOK {
		// Do not propagate Google's error body (may contain client context);
		// log servers see it via the caller, clients get a generic failure.
		return GoogleIdentity{}, fmt.Errorf("%w: status %d", ErrGoogleExchangeFailed, res.StatusCode)
	}

	var tokenRes googleTokenResponse
	if err := json.Unmarshal(body, &tokenRes); err != nil {
		return GoogleIdentity{}, fmt.Errorf("%w: %v", ErrGoogleExchangeFailed, err)
	}
	if tokenRes.IDToken == "" {
		return GoogleIdentity{}, ErrGoogleMissingIDToken
	}

	return g.verifyIDToken(ctx, tokenRes.IDToken, expectedNonce)
}

// verifyIDToken parses and fully validates a Google id_token.
func (g *GoogleClient) verifyIDToken(ctx context.Context, idToken, expectedNonce string) (GoogleIdentity, error) {
	claims := &googleIDClaims{}
	keyfunc := func(token *jwt.Token) (interface{}, error) {
		// Restrict to RS256 — Google always signs id_tokens with RS256.
		if _, ok := token.Method.(*jwt.SigningMethodRSA); !ok || token.Method.Alg() != jwt.SigningMethodRS256.Alg() {
			return nil, ErrGoogleInvalidIDToken
		}
		kid, _ := token.Header["kid"].(string)
		if kid == "" {
			return nil, ErrGoogleUnknownKeyID
		}
		key, err := g.publicKey(ctx, kid)
		if err != nil {
			return nil, err
		}
		return key, nil
	}

	token, err := jwt.ParseWithClaims(idToken, claims, keyfunc,
		jwt.WithValidMethods([]string{jwt.SigningMethodRS256.Alg()}),
		jwt.WithAudience(g.clientID),
		jwt.WithExpirationRequired(),
	)
	if err != nil {
		return GoogleIdentity{}, fmt.Errorf("%w: %v", ErrGoogleInvalidIDToken, err)
	}
	if !token.Valid {
		return GoogleIdentity{}, ErrGoogleInvalidIDToken
	}
	// Issuer must be Google (both forms accepted per OIDC discovery doc).
	if claims.Issuer != "https://accounts.google.com" && claims.Issuer != "accounts.google.com" {
		return GoogleIdentity{}, ErrGoogleUnexpectedIssuer
	}
	// Nonce binds the id_token to THIS flow's state row (anti replay/mix-up).
	if claims.Nonce == "" || claims.Nonce != expectedNonce {
		return GoogleIdentity{}, ErrGoogleNonceMismatch
	}
	if claims.Subject == "" || claims.Email == "" {
		return GoogleIdentity{}, ErrGoogleInvalidIDToken
	}
	if !claims.EmailVerified {
		return GoogleIdentity{}, ErrGoogleEmailUnverified
	}
	return GoogleIdentity{
		Subject:       claims.Subject,
		Email:         strings.ToLower(claims.Email),
		EmailVerified: claims.EmailVerified,
		Name:          claims.Name,
	}, nil
}

// publicKey returns the RSA key for a kid, using the cached JWKS and
// refetching once when the kid is unknown (key rotation).
func (g *GoogleClient) publicKey(ctx context.Context, kid string) (*rsa.PublicKey, error) {
	g.mu.RLock()
	key, ok := g.jwks[kid]
	stale := time.Since(g.jwksFetch) > jwksCacheTTL
	g.mu.RUnlock()
	if ok && !stale {
		return key, nil
	}
	if err := g.refreshJWKS(ctx); err != nil {
		return nil, err
	}
	g.mu.RLock()
	key, ok = g.jwks[kid]
	g.mu.RUnlock()
	if !ok {
		return nil, ErrGoogleUnknownKeyID
	}
	return key, nil
}

// googleJWKS is the JWKS document shape (RSA keys only).
type googleJWKS struct {
	Keys []struct {
		Kty string `json:"kty"`
		Kid string `json:"kid"`
		N   string `json:"n"`
		E   string `json:"e"`
	} `json:"keys"`
}

func (g *GoogleClient) refreshJWKS(ctx context.Context) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, googleJWKSURL, nil)
	if err != nil {
		return err
	}
	res, err := g.http.Do(req)
	if err != nil {
		return fmt.Errorf("%w: %v", ErrGoogleJWKSUnavailable, err)
	}
	defer res.Body.Close()
	body, err := io.ReadAll(io.LimitReader(res.Body, 1<<20))
	if err != nil {
		return fmt.Errorf("%w: %v", ErrGoogleJWKSUnavailable, err)
	}
	if res.StatusCode != http.StatusOK {
		return fmt.Errorf("%w: status %d", ErrGoogleJWKSUnavailable, res.StatusCode)
	}
	var doc googleJWKS
	if err := json.Unmarshal(body, &doc); err != nil {
		return fmt.Errorf("%w: %v", ErrGoogleJWKSUnavailable, err)
	}
	keys := make(map[string]*rsa.PublicKey, len(doc.Keys))
	for _, k := range doc.Keys {
		if k.Kty != "RSA" || k.N == "" || k.E == "" {
			continue
		}
		nBytes, err := base64.RawURLEncoding.DecodeString(k.N)
		if err != nil {
			continue
		}
		eBytes, err := base64.RawURLEncoding.DecodeString(k.E)
		if err != nil {
			continue
		}
		exponent := 0
		for _, b := range eBytes {
			exponent = exponent<<8 + int(b)
		}
		keys[k.Kid] = &rsa.PublicKey{N: new(big.Int).SetBytes(nBytes), E: exponent}
	}
	g.mu.Lock()
	g.jwks = keys
	g.jwksFetch = time.Now()
	g.mu.Unlock()
	return nil
}
